# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

# https://goreleaser.com/customization/builds/go
builds:
  - id: linux-windows
    goos: [linux, windows]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    # Separating the macos builds so that we can exclude them from cosign
    # (since the binary is manupilated by the notarization process).
  - id: darwin
    goos: [darwin]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]

# https://goreleaser.com/customization/archive
archives:
  - id: archives
    formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - CHANGELOG.md
      - README.md
      # Note: The "*" makes the file optional, since the macos builds
      # are not signed by Cosign.
      - src: "{{ .ArtifactPath }}.sig*"
        strip_parent: true
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

# https://goreleaser.com/customization/checksum
checksum:
  name_template: checksums.txt

# https://goreleaser.com/customization/changelog
changelog:
  disable: true # Handled by release-please

# https://goreleaser.com/customization/notarize
notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{ .Env.MACOS_SIGN_P12 }}"
        password: "{{ .Env.MACOS_SIGN_PASSWORD }}"
      notarize:
        issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
        key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
        key: "{{ .Env.MACOS_NOTARY_KEY }}"

# https://goreleaser.com/customization/binary_sign
binary_signs:
  - id: cosign-binaries
    # Annoyingly, build_signs runs before notarize, which messes with the
    # macos builds, so we only sign linux and windows builds.
    ids: [linux-windows]
    signature: "${artifact}.sig"
    cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    args:
      - sign-blob
      - --key=env://COSIGN_KEY
      - --output-signature=${signature}
      - ${artifact}
      - --yes

# https://goreleaser.com/customization/sign
signs:
  - id: cosign-checksum
    cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    args:
      - sign-blob
      - --key=env://COSIGN_KEY
      - --output-signature=${signature}
      - ${artifact}
      - --yes
    artifacts: checksum

# https://goreleaser.com/customization/release
release:
  ids: [archives, cosign-checksum]

# https://goreleaser.com/customization/homebrew_casks
homebrew_casks:
  - ids: [archives]
    repository:
      owner: armsnyder
      name: homebrew-tap
