# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    groups:
      Go:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    groups:
      Actions:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /vscode-extension
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    groups:
      NPM:
        patterns: ["*"]
