# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Release
on:
  push:
    tags: ["v*"]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
      - name: Create app token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Build and upload assets
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --config .github/.goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          MACOS_SIGN_P12: ${{ secrets.MACOS_SIGN_P12 }}
          MACOS_SIGN_PASSWORD: ${{ secrets.MACOS_SIGN_PASSWORD }}
          MACOS_NOTARY_KEY: ${{ secrets.MACOS_NOTARY_KEY }}
          MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
          MACOS_NOTARY_ISSUER_ID: ${{ secrets.MACOS_NOTARY_ISSUER_ID }}
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}
      - name: Install dependencies
        run: npm ci
        working-directory: vscode-extension
      - name: Publish VSCode extension
        run: npm run publish -- $(cat ../version.txt)
        working-directory: vscode-extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
