# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: VSCode Extension CI
on:
  push:
    branches: [main]
    paths:
      - 'vscode-extension/**'
      - '.github/workflows/ci-vscode.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'vscode-extension/**'
      - '.github/workflows/ci-vscode.yaml'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
        working-directory: vscode-extension
      - name: Check types
        run: npm run typecheck
        working-directory: vscode-extension
      - name: Lint
        run: npm run lint
        working-directory: vscode-extension
      - name: Check formatting
        run: npm run format:check
        working-directory: vscode-extension
      - name: Test packaging
        run: npm run package
        working-directory: vscode-extension
      - name: Run tests
        run: xvfb-run -a npm test
        working-directory: vscode-extension
